/-
Prints the protected soundness statements of CGV, one block per constant, in a
fixed order. CI compares the output with the committed manifest
`cgv/prover/protected-statements.txt`; any difference fails the build.

  lake build ContractGraph ContractGraph.Main
  lake env lean --run scripts/ProtectedStatements.lean > protected-statements.txt

What is printed:
* every theorem in `protectedTheorems`: its statement (type);
* every definition in `protectedDefinitions`, and every non-theorem
  `ContractGraph.*` constant their types or values reach: its type, plus a
  structural hash of its value. Inductive types list their constructors.

Proofs are never printed, so rewriting a proof leaves the manifest unchanged.
The list of names mirrors the CGV table in `.claude/rules/protected-surfaces.md`;
keep the two in step.
-/
import Lean
open Lean Meta

def protectedTheorems : List Name := [
  `ContractGraph.checkEdge_sound,
  `ContractGraph.checkEdgeAll_sound,
  `ContractGraph.checkEdgeAll_sound_noErrors,
  `ContractGraph.checkPath_sound,
  `ContractGraph.checkPath_sound_noErrors,
  `ContractGraph.enumeratePaths_complete,
  `ContractGraph.closedStates_checkPath,
  `ContractGraph.runChecker_sound,
  `ContractGraph.runChecker_sound_all,
  `ContractGraph.runChecker_exitCode_eq_zero_iff,
  `ContractGraph.runCheckerPaths_exitCode_eq_zero_iff,
  `ContractGraph.incompleteWith_exitCode
]

def protectedDefinitions : List Name := [
  `ContractGraph.constraintImplies,
  `ContractGraph.IsDataPath,
  `ContractGraph.stepwiseSound
]

def inScope (n : Name) : Bool :=
  (`ContractGraph).isPrefixOf n

/-- Constants a definition's meaning depends on: those in its type and value,
and for an inductive type its constructors. Theorems are skipped: their proofs
do not change what a definition means. -/
def dependencies (ci : ConstantInfo) : Array Name :=
  let fromExprs := ci.type.getUsedConstants ++ (ci.value?.map (·.getUsedConstants) |>.getD #[])
  match ci with
  | .inductInfo v => fromExprs ++ v.ctors.toArray
  | _ => fromExprs

/-- Every in-scope, non-theorem constant reachable from `roots`, sorted. -/
partial def reach (env : Environment) (roots : List Name) : Array Name := Id.run do
  let mut seen : NameSet := {}
  let mut todo := roots
  while !todo.isEmpty do
    match todo with
    | [] => pure ()
    | n :: rest =>
      todo := rest
      if seen.contains n then continue
      match env.find? n with
      | none => continue
      | some (.thmInfo _) => continue
      | some ci =>
        seen := seen.insert n
        for d in dependencies ci do
          if inScope d && !seen.contains d then todo := d :: todo
  return seen.toArray.qsort Name.lt

def kindOf : ConstantInfo → String
  | .thmInfo _ => "theorem"
  | .defnInfo _ => "def"
  | .opaqueInfo _ => "opaque"
  | .axiomInfo _ => "axiom"
  | .inductInfo _ => "inductive"
  | .ctorInfo _ => "constructor"
  | .recInfo _ => "recursor"
  | .quotInfo _ => "quot"

def render (env : Environment) : MetaM String := do
  let mut out := "-- Generated by cgv/prover/scripts/ProtectedStatements.lean. Do not edit by hand.\n"
  out := out ++ "-- A change here is a change to CGV's guarantee: see .claude/rules/protected-surfaces.md.\n"
  out := out ++ "\n-- Protected theorem statements\n"
  for n in protectedTheorems do
    let some ci := env.find? n | throwError "protected theorem {n} not found"
    unless ci matches .thmInfo _ do throwError "{n} is not a theorem"
    out := out ++ s!"\ntheorem {n} :\n  {← ppExpr ci.type}\n"
  out := out ++ "\n-- Protected definitions and every ContractGraph definition they reach\n"
  for n in protectedDefinitions do
    unless env.contains n do throwError "protected definition {n} not found"
  for n in reach env protectedDefinitions do
    let some ci := env.find? n | unreachable!
    let valueHash := match ci.value? with
      | some v => s!"\n  value hash {hash v}"
      | none => ""
    out := out ++ s!"\n{kindOf ci} {n} :\n  {← ppExpr ci.type}{valueHash}\n"
  return out

def main : IO UInt32 := do
  initSearchPath (← findSysroot)
  let env ← importModules #[{ module := `ContractGraph }, { module := `ContractGraph.Main }] {}
  let opts : Options := Options.empty |>.set `format.width (100 : Nat)
  let ctx : Core.Context := { fileName := "<ProtectedStatements>", fileMap := default, options := opts }
  let (out, _) ← (render env).run' {} |>.toIO ctx { env }
  IO.print out
  return 0
