#!/usr/bin/env python3
"""Acceptance scenario runner — TEMPLATE.

docs/assurance/acceptance/run_acceptance.py

Layer 5 (empirical) — user-perspective proxy.
Generated by: /crosscheck:acceptance-oracle-draft

Loads scenarios from scenarios.yaml and executes the mechanically-verifiable
ones, reporting pass/fail for each assertion without requiring human
judgement.

This file is a TEMPLATE. The infrastructure (loader, result types, CLI,
summary printing) is generic and reusable. The per-scenario runner
functions in `_RUNNERS` are domain-specific — replace them with runners
that exercise your own modules.

The QUEUE-001 runner below is wired and runnable against a hypothetical
``queue.work_queue`` module to demonstrate the pattern. The QUEUE-002
runner is a skeleton that returns SKIP — fill it in before enabling in
CI.

Usage
-----
    python docs/assurance/acceptance/run_acceptance.py
    python docs/assurance/acceptance/run_acceptance.py --flow work-queue
    python docs/assurance/acceptance/run_acceptance.py --scenario QUEUE-001
    python docs/assurance/acceptance/run_acceptance.py --fail-fast

Exit codes
----------
0   All assertions passed (or skipped).
1   One or more assertions failed.
2   Setup or configuration error.

CI integration
--------------
Add to .github/workflows/assurance.yml as a non-blocking job initially:

    - name: Acceptance scenarios
      run: python docs/assurance/acceptance/run_acceptance.py
      continue-on-error: true  # remove once scenarios prove stable

Notes on "verifiable: false" assertions
----------------------------------------
Assertions marked verifiable: false in scenarios.yaml are skipped by this
runner. They are documented stubs — human TODOs to quantify the acceptance
criterion before the assertion can be gated in CI.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
import traceback
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

SCENARIOS_PATH = Path(__file__).parent / "scenarios.yaml"

# ─── Result types ─────────────────────────────────────────────────────────────

@dataclass
class AssertionResult:
    scenario_id: str
    assertion_id: str
    description: str
    passed: bool
    skipped: bool = False
    skip_reason: str = ""
    error: Optional[str] = None


@dataclass
class ScenarioResult:
    scenario_id: str
    name: str
    flow: str
    assertions: list[AssertionResult] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return all(a.passed or a.skipped for a in self.assertions)

    @property
    def failed_assertions(self) -> list[AssertionResult]:
        return [a for a in self.assertions if not a.passed and not a.skipped]


# ─── Per-scenario runners ─────────────────────────────────────────────────────
#
# Each runner returns a list[AssertionResult]. Add one function per scenario
# id in scenarios.yaml. The function name convention is _run_<lowercase id>.

def _run_queue_001() -> list[AssertionResult]:
    """QUEUE-001: FIFO ordering preserved across enqueue/dequeue.

    Replace the import below with the path to your work-queue module. The
    logic itself — enqueue three items, dequeue all, check order/size/dups —
    is generic to any FIFO queue with the standard interface.
    """
    results = []
    try:
        # Replace with your module:
        from queue.work_queue import WorkQueue  # type: ignore[import-not-found]

        q = WorkQueue()
        for item in ("A", "B", "C"):
            q.enqueue(item)

        dequeued = []
        while q.size() > 0:
            dequeued.append(q.dequeue())

        # A1: order
        ordered = dequeued == ["A", "B", "C"]
        results.append(AssertionResult(
            "QUEUE-001", "QUEUE-001-A1", "Dequeue produces items in enqueue order",
            passed=ordered,
            error=None if ordered else f"got {dequeued}, expected ['A', 'B', 'C']",
        ))

        # A2: empty after drain
        empty = q.size() == 0
        results.append(AssertionResult(
            "QUEUE-001", "QUEUE-001-A2", "Queue is empty after all items dequeued",
            passed=empty,
            error=None if empty else f"size={q.size()} after drain",
        ))

        # A3: no duplicates
        unique = len(dequeued) == len(set(dequeued))
        results.append(AssertionResult(
            "QUEUE-001", "QUEUE-001-A3", "No item is delivered more than once",
            passed=unique,
            error=None if unique else f"duplicates: {dequeued}",
        ))
    except Exception as exc:
        results.append(AssertionResult(
            "QUEUE-001", "QUEUE-001-SETUP", "Setup",
            passed=False, error=f"setup error: {exc}\n{traceback.format_exc()}",
        ))
    return results


def _run_queue_002() -> list[AssertionResult]:
    """QUEUE-002: Failed-terminal items land in dead-letter (template stub).

    This runner is a skeleton — fill it in for your queue's retry semantics.
    The shape: enqueue an item that always fails, drive max_retries+1
    failures, then assert the item is in dead_letter() and NOT in
    snapshot(), and that subsequent dequeue calls don't return it.
    """
    return [AssertionResult(
        "QUEUE-002", "QUEUE-002-A1", "Failed-terminal item in dead-letter",
        passed=False, skipped=True,
        skip_reason=(
            "QUEUE-002 is a template skeleton. Wire it to your queue's retry "
            "harness (a fixture that drives max_retries+1 failures on a poison "
            "item) before enabling in CI."
        ),
    )]


# Map scenario IDs to runner functions. Add an entry for every scenario in
# scenarios.yaml. Scenarios without a registered runner are skipped with a
# warning — useful while scenarios are still being authored.
_RUNNERS: dict[str, Any] = {
    "QUEUE-001": _run_queue_001,
    "QUEUE-002": _run_queue_002,
}


# ─── CLI ──────────────────────────────────────────────────────────────────────

def _load_scenarios(flow: Optional[str] = None, scenario: Optional[str] = None) -> list[dict]:
    raw = yaml.safe_load(SCENARIOS_PATH.read_text())
    items = raw.get("scenarios", [])
    if scenario:
        items = [s for s in items if s["id"] == scenario]
    elif flow:
        items = [s for s in items if s["flow"] == flow]
    return items


def _fmt_status(r: AssertionResult) -> str:
    if r.skipped:
        return "SKIP"
    return "PASS" if r.passed else "FAIL"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run acceptance scenarios")
    parser.add_argument("--flow", help="Filter to a specific flow")
    parser.add_argument("--scenario", help="Run a single scenario by ID")
    parser.add_argument("--fail-fast", action="store_true", help="Stop on first failure")
    args = parser.parse_args()

    scenarios = _load_scenarios(flow=args.flow, scenario=args.scenario)
    if not scenarios:
        print("ERROR: No scenarios matched the filter.", file=sys.stderr)
        return 2

    all_results: list[ScenarioResult] = []
    for spec in scenarios:
        sid = spec["id"]
        runner = _RUNNERS.get(sid)
        if runner is None:
            print(f"  WARN: no runner registered for {sid} — skipping")
            continue

        sr = ScenarioResult(
            scenario_id=sid,
            name=spec.get("name", sid),
            flow=spec.get("flow", ""),
        )
        sr.assertions = runner()
        all_results.append(sr)

        print(f"\n{'─'*60}")
        print(f"  Scenario: {sid} — {sr.name}")
        print(f"  Flow:     {sr.flow}")
        for ar in sr.assertions:
            status = _fmt_status(ar)
            line = f"  [{status}] {ar.assertion_id}: {ar.description}"
            print(line)
            if ar.error:
                for el in ar.error.splitlines():
                    print(f"           {el}")
            if ar.skipped and ar.skip_reason:
                print(f"           ↳ {textwrap.shorten(ar.skip_reason, width=70)}")

        outcome = "PASS" if sr.passed else "FAIL"
        print(f"  Result:   {outcome}")

        if args.fail_fast and not sr.passed:
            print("\nFail-fast: stopping.", file=sys.stderr)
            return 1

    # Summary
    total = sum(len(sr.assertions) for sr in all_results)
    passed = sum(
        1 for sr in all_results for a in sr.assertions if a.passed
    )
    skipped = sum(
        1 for sr in all_results for a in sr.assertions if a.skipped
    )
    failed = sum(
        1 for sr in all_results for a in sr.assertions
        if not a.passed and not a.skipped
    )

    print(f"\n{'='*60}")
    print(f"  Assertions: {total}  Passed: {passed}  Skipped: {skipped}  Failed: {failed}")
    scenarios_passed = sum(1 for sr in all_results if sr.passed)
    print(f"  Scenarios:  {len(all_results)}  Passed: {scenarios_passed}  Failed: {len(all_results) - scenarios_passed}")
    print("="*60)

    if failed > 0:
        print("\nSome assertions FAILED. See details above.", file=sys.stderr)
        return 1

    print("\nAll verifiable assertions PASSED (skipped assertions need fixture wiring).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
